FILE_PATH:
 RAW_DATA: "MDA133PredictorTrainAndValidation.xls"
 LABEL: "MDA133CompleteInfo20070319.xls"
 PROCESSED_DATA: 


PRODUCE_DATA: True

FEATURE:
 NUM: 110
 NUM_TTEST: 110
 NUM2: 100
 NUM_TTEST2: 100



