FILE_PATH:
 RAW_DATA: "MDA133PredictorTrainAndValidation.xls"
 LABEL: "MDA133CompleteInfo20070319.xls"
 PROCESSED_DATA: 

POS_NAME: pCR
NEG_NAME: RD

PRODUCE_DATA: True

FEATURE:
 NUM: 100
 NUM_TTEST: 100
 NUM2: 100
 NUM_TTEST2: 100



